import math

EXCHANGES_COUNT = 2
ZERO_INTELLIGENCE_COUNT = int(66)

SESSION_LENGTH = int(12e3)
INTENSITY = 0.0005
POISSON_STEP = int(1e5)

INITIAL_ASSET_PRICE = 1e4
MEAN_REVERSION_FACTOR = 0.05
SIGMA_ASSET = math.sqrt(5e6)
SIGMA_UTILITY = math.sqrt(5e6)
QUANTITY_MAX = 10
SHADING_MIN = 0
SHADING_MAX = 0

NBBO_DELAY = 0
